### ISSUE TITLE
Supertux master fails to compile with glbinding master

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#74]
It seems I get this error after building with cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DCMAKE_PREFIX_PATH=$INSTALLDIR  -DGLBINDING_ENABLED=ON -DCMAKE_BUILD_TYPE=RELEASE

[ 91%] Building CXX object CMakeFiles/supertux2.dir/src/video/texture_manager.cpp.o
/srcbuild/supertux/src/video/gl/gl_renderer.cpp: In constructor ‘GLRenderer::GLRenderer()’:
/srcbuild/supertux/src/video/gl/gl_renderer.cpp:78:14: error: ‘glbinding::Binding’ has not been declared
   glbinding::Binding::initialize();
              ^
CMakeFiles/supertux2.dir/build.make:6072: recipe for target 'CMakeFiles/supertux2.dir/src/video/gl/gl_renderer.cpp.o' failed
make[2]: *** [CMakeFiles/supertux2.dir/src/video/gl/gl_renderer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:61: recipe for target 'CMakeFiles/supertux2.dir/all' failed
make[1]: *** [CMakeFiles/supertux2.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 381 seconds

**Comment by n3rdopolis** [comment]
It seems that it still compiles with  glbinding's v1.0.5  tag

**Comment by tobbi** [comment]
@scheibel Any idea what we need to do, or can you provide a patch?

**Comment by tobbi** [comment]
So, just for reference: I added the relevant include for glbinding to SuperTux. I hope it still compiles with earlier versions of glbinding, that I did not check.

**Comment by scheibel** [comment]
It seems like your findings are correct. We cleaned up the include structure of glbinding and it is actually possible that i have chosen the *wrong* one with my PR. ```#include <glbinding/Binding.h>``` should work with each release of glbinding (1.0 and later).
